language: node_js
node_js:
  - 14.3
  
services:
  - docker

env:
  - CI=false
install:
  - npm install
  
script:
  - npm run build
  
after_script:
  - docker login -u harshal.marathe@thinkanalytics.in -p Ichigo@2020
  - docker build build/. -t harshalthink/jenk-frontend-demo
  - docker push harshalthink/jenk-frontend-demo
